apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
    inbound:
        - name: estate-server
          port: 8080
          type: REST
          networkVisibility: Public
          context: /
